name = 'KITTI_data_road';

basedir = '~/var/data/KITTI/data_road/';

testimgdir = 'testing/image/';

postraindir = 'training/patches/pos/';
negtraindir = 'training/patches/neg/';

modeldir = '../';
traindir = '../';

%----------

%Feature options
hogcellsize = 17;
hogorient = 9;
patchsize = 3;

%LibLinear options
lltype = 2;
llc = 1e2;

%Randforest options
tbsize = 30;

kitti_data_road = ...
	struct('name', name, ...
		   'base', basedir, ...
		   'modeldir', modeldir, ...
		   'traindir', traindir, ...
		   'tests', testimgdir, ...
		   'positives', postraindir, ...
		   'negatives', negtraindir, ...
		   'hogcellsize', hogcellsize, ...
		   'hogorientations', hogorient, ...
		   'patchsize', patchsize, ...
		   'lltype', lltype, ...
		   'llc', llc, ...
		   'tbsize', tbsize ...
		  );


clear name basedir testimgdir postraindir negtraindir modeldir traindir
clear hogcellsize hogorient patchsize lltype llc tbsize