name         = 'KITTI_GCPR';

basedir      = '~/var/media/Elements/var/data/KITTI/';

testbasedir  = '~/var/media/Elements/var/data/KITTI/data_road/';

testfilelist = {{'training/test.txt'}};

trainfilelist = {{ ...
	'city/kitti5001/train.txt', ...
	'city/kitti5002/train.txt', ...
	'city/kitti5005/train.txt', ...
	'city/kitti5009/train.txt', ...
	'city/kitti5011/train.txt', ...
	'city/kitti5013/train.txt', ...
	'city/kitti5014/train.txt', ...
	'city/kitti5017/train.txt', ...
	'city/kitti5018/train.txt', ...
	'city/kitti5048/train.txt', ...
	'city/kitti5051/train.txt', ...
	'city/kitti5056/train.txt', ...
	'city/kitti5059/train.txt', ...
	'city/kitti5060/train.txt', ...
	'city/kitti5084/train.txt', ...
	'city/kitti6091/train.txt', ...
	'city/kitti6093/train.txt', ...
	'city/kitti6095/train.txt', ...
	'city/kitti6096/train.txt', ...
	'city/kitti6104/train.txt', ...
	'city/kitti6106/train.txt', ...
	'city/kitti6113/train.txt', ...
	'city/kitti6117/train.txt', ...
	'city/kitti7001/train.txt', ...
	'city/kitti7002/train.txt', ...
	'city/kitti7026/train.txt', ...
	'city/kitti7071/train.txt' ...
}};


modeldir = './';
traindir = './';

%----------

%Feature options
hogcellsize = 17;
hogorient   = 9;
patchsize   = 3;

%LibLinear options
lltype = 2;
llc    = 1e2;

%Randforest options
tbsize = 30;

kitti_gcpr = ...
	struct('name', name, ...
		   'base', basedir, ...
		   'testbase', testbasedir, ...
		   'modeldir', modeldir, ...
		   'traindir', traindir, ...
		   'hogcellsize', hogcellsize, ...
		   'hogorientations', hogorient, ...
		   'patchsize', patchsize, ...
		   'lltype', lltype, ...
		   'llc', llc, ...
		   'tbsize', tbsize, ...
		   'trainlists', trainfilelist, ...
		   'testlists', testfilelist ...
		  );


clear name basedir testimgdir modeldir traindir testbasedir testfilelist
clear hogcellsize hogorient patchsize lltype llc tbsize trainfilelist
