name         = 'KITTI_GCPR';

basedir      = '~/var/media/Elements/var/data/KITTI/';

testbasedir  = '~/var/media/Elements/var/data/KITTI/data_road/';

testfilelist = {{'training/train.txt'}};

trainfilelist = {{ ...
	'road/kitti3029/train.txt', ...
	'road/kitti3070/train.txt', ...
	'city/kitti5011/train.txt' ...
}};


modeldir = './';
traindir = './';

%----------

%Feature options
hogcellsize = 17;
hogorient   = 9;
patchsize   = 3;

%LibLinear options
lltype = 2;
llc    = 1e2;

%Randforest options
tbsize = 30;

kitti_residential = ...
	struct('name', name, ...
		   'base', basedir, ...
		   'testbase', testbasedir, ...
		   'modeldir', modeldir, ...
		   'traindir', traindir, ...
		   'hogcellsize', hogcellsize, ...
		   'hogorientations', hogorient, ...
		   'patchsize', patchsize, ...
		   'lltype', lltype, ...
		   'llc', llc, ...
		   'tbsize', tbsize, ...
		   'trainlists', trainfilelist, ...
		   'testlists', testfilelist ...
		  );


clear name basedir testimgdir modeldir traindir testbasedir testfilelist
clear hogcellsize hogorient patchsize lltype llc tbsize trainfilelist